/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainframeGame;

import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Jelo
 */
public class EasyLevel extends javax.swing.JFrame {

    private DataStore dStore = new DataStore();
    private static int score, questionCounter;

    public EasyLevel() {
        initComponents();

        correct.setVisible(false);
        incorrect.setVisible(false);

        dStore.fillList();

        questionLabel.setText(dStore.getQuestion(questionCounter));
        optionA.setText(dStore.getoptionA());
        optionB.setText(dStore.getoptionB());
        optionC.setText(dStore.getoptionC());
        optionD.setText(dStore.getoptionD());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JLabel();
        quit = new javax.swing.JLabel();
        levels = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        optionC = new javax.swing.JLabel();
        optionD = new javax.swing.JLabel();
        optionA = new javax.swing.JLabel();
        optionB = new javax.swing.JLabel();
        correct = new javax.swing.JLabel();
        scoreVariable = new javax.swing.JLabel();
        incorrect = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, 30));

        quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitMouseClicked(evt);
            }
        });
        getContentPane().add(quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, 20));

        levels.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(levels, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 70, 40));

        questionLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(136, 168, 230));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 230, 560, 60));

        optionC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionC.setForeground(new java.awt.Color(136, 168, 230));
        optionC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionCMouseClicked(evt);
            }
        });
        getContentPane().add(optionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 240, 60));

        optionD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionD.setForeground(new java.awt.Color(136, 168, 230));
        optionD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionDMouseClicked(evt);
            }
        });
        getContentPane().add(optionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 240, 60));

        optionA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionA.setForeground(new java.awt.Color(136, 168, 230));
        optionA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionAMouseClicked(evt);
            }
        });
        getContentPane().add(optionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 240, 60));

        optionB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        optionB.setForeground(new java.awt.Color(136, 168, 230));
        optionB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionBMouseClicked(evt);
            }
        });
        getContentPane().add(optionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 240, 60));

        correct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainframeGame/correct.png"))); // NOI18N
        getContentPane().add(correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 203, 63));

        scoreVariable.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        scoreVariable.setForeground(new java.awt.Color(136, 138, 230));
        scoreVariable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreVariable.setText("0");
        getContentPane().add(scoreVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 50, 40));

        incorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainframeGame/incorrect.png"))); // NOI18N
        getContentPane().add(incorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 203, 63));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainframeGame/GameArena.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 652));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 652));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_quitMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        this.setVisible(false);
        Home.home.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    public void incrementScore() {
        scoreVariable.setText(++score + "");
     }

    public void goToNextQuestion() {
        questionCounter++;
        questionLabel.setText(dStore.getQuestion(questionCounter));
        optionA.setText(dStore.getoptionA());
        optionB.setText(dStore.getoptionB());
        optionC.setText(dStore.getoptionC());
        optionD.setText(dStore.getoptionD());
    }

    public void keepScoreConstant() {
        //do nothing
    }

    public boolean isTheLastQuestion() {
        return questionCounter == 4;
    }

    public void displayWinningBoard() {
        WinningBoard1 wBoard = new WinningBoard1();
        wBoard.setVisible(true);
    }

    public static int getScore() {
        return score;
    }

    private void resetCounter() {
        questionCounter = 0;
        score=0;
    }

    private boolean isOptionCorrect(JLabel label) {

        String correctAnswer = dStore.getQuestionAndAnswerList().get(questionCounter).get(5);
        return label.getText().equals(correctAnswer);
    }

    public void performAction(JLabel label)  {

        if (isOptionCorrect(label)) {
            correct.setVisible(true);
            incrementScore();

            new Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    correct.setVisible(false);
                }
            }, 500);

            if (isTheLastQuestion()) {
                displayWinningBoard();
                resetCounter();
            } else {
                goToNextQuestion();
            }
        } else {
            incorrect.setVisible(true);
            keepScoreConstant();

            new Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    incorrect.setVisible(false);
                }
            }, 500);

            if (isTheLastQuestion()) {
                displayWinningBoard();
                resetCounter();
            } else {
                goToNextQuestion();

            }
        }
    }

    private void optionAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionAMouseClicked
     
            performAction(optionA);
    
    }//GEN-LAST:event_optionAMouseClicked

    private void optionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionCMouseClicked
       
            performAction(optionC);
   
    }//GEN-LAST:event_optionCMouseClicked

    private void optionBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionBMouseClicked
 
            performAction(optionB);
    
    }//GEN-LAST:event_optionBMouseClicked

    private void optionDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionDMouseClicked
      
            performAction(optionD);
      
    }//GEN-LAST:event_optionDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyLevel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correct;
    private javax.swing.JLabel home;
    private javax.swing.JLabel incorrect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel optionA;
    private javax.swing.JLabel optionB;
    private javax.swing.JLabel optionC;
    private javax.swing.JLabel optionD;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel quit;
    private javax.swing.JLabel scoreVariable;
    // End of variables declaration//GEN-END:variables
}
